name: "Slack Release Notifier"
author: "Fede Calendino"
description: "Notify a slack channel about a new release"
inputs:
  slack_webhook_url:
    description: "URL provided by Slack's Incoming WebHooks app."
    required: true
  pypi_project_url:
    description: "URL of the project in pypi.org. If present a link to it will be added in the notification."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'package'
  color: 'green'
